name: Mirror to GitLab

on:
  push:
    branches: ['**']
    tags: ['*']
  delete:
    branches: ['**']
    tags: ['*']
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: zhdk-icst/mirror-to-gitlab@v1
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
